version: 0.2
# Build AMI from Packer template

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - apt-get -y update
      - apt-get -y install build-essential ruby-dev git curl build-essential libxml2-dev libxslt-dev libssl-dev autoconf jq wget
      - wget https://packages.chef.io/files/stable/chefdk/3.1.0/ubuntu/14.04/chefdk_3.1.0-1_amd64.deb
      - dpkg -i chefdk_3.1.0-1_amd64.deb
      - wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
      - unzip packer_1.2.5_linux_amd64.zip -d /usr/local/bin

  build:
    commands:
      - echo Building AMI
      - packer build -var-file=packer/ami_params.json -var git_hash=${CODEBUILD_RESOLVED_SOURCE_VERSION} packer/ami.json --chef-license accept
      - echo Creating Test Instance Configuration
      - cat manifest.json
      - chmod +x buildscripts/generate_instance_config.sh
      - ./buildscripts/generate_instance_config.sh

artifacts:
  files:
    - "**/*"