version: 0.2

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - apt-get -y update
      - apt-get -y install build-essential ruby-dev git curl build-essential libxml2-dev libxslt-dev libssl-dev autoconf jq
      - curl -L https://www.opscode.com/chef/install.sh | bash
      - /opt/chef/embedded/bin/gem install berkshelf --no-ri --no-rdoc
      - ln -s /opt/chef/embedded/bin/berks /usr/local/bin/berks
      - wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
      - unzip packer_1.2.5_linux_amd64.zip -d /usr/local/bin

  build:
    commands:
      - echo Building AMI
      - packer build -var-file=packer/ami_params.json -var git_hash=${CODEBUILD_SOURCE_VERSION} packer/ami.json
      - echo Creating Test Instance Configuration
      - cat manifest.json
      - chmod +x buildscripts/generate_instance_config.sh
      - ./buildscripts/generate_instance_config.sh

artifacts:
  files:
    - "**/*"