version: 0.2
# Publish AMI ID to SSM Parameter Store

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install jq
  build:
    commands:
      - AmiId=$(cat cfn/test-instance-config.json | jq -r '.Parameters.AmiId')
      - aws ssm put-parameter --name "/packerdemo/packer_ami_pipeline/LatestAMI" --value $AmiId --type String --overwrite