version: 0.2

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - apt-get -y update
      - apt-get -y install build-essential ruby-dev git curl build-essential libxml2-dev libxslt-dev libssl-dev autoconf jq
      - curl -L https://www.opscode.com/chef/install.sh | bash
      - /opt/chef/embedded/bin/gem install berkshelf --no-ri --no-rdoc
      - ln -s /opt/chef/embedded/bin/berks /usr/local/bin/berks
  build:
    commands:
      - aws cloudformation describe-stacks --stack-name AMIPipelineTestInstance --output text --query 'Stacks[0].Outputs[*].OutputValue'