version: 0.2

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
      - unzip packer_1.2.5_linux_amd64.zip -d /usr/local/bin
  build:
    commands:
      - echo Building AMI
      - packer build -var-file=packer/ami_params.json packer/ami.json