version: 0.2

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - apt-get -y update
      - apt-get -y install build-essential ruby-dev git curl build-essential libxml2-dev libxslt-dev libssl-dev autoconf jq wget
      - wget https://packages.chef.io/files/stable/chefdk/3.1.0/ubuntu/14.04/chefdk_3.1.0-1_amd64.deb
      - dpkg -i chefdk_3.1.0-1_amd64.deb
  build:
    commands:
      - OUTPUTS=$(aws cloudformation describe-stacks --stack-name AMIPipelineTestInstance --output json --region us-east-1 | jq 'reduce .Stacks[0].Outputs[] as $item ({}; . + {"\($item.OutputKey)":$item.OutputValue})')
      - echo "$OUTPUTS"
      - TestInstanceId=$(echo $OUTPUTS | jq '.TestInstanceId')
      - echo "$TestInstanceId"
      - TestInstanceIPAddress=$(echo $OUTPUTS | jq '.TestInstanceIPAddress')
      - echo "$TestInstanceIPAddress"
      - cat test/test-instance-config.json
      - AmiId=$(cat test/test-instance-config.json | jq '.AmiId')
      - echo "$AmiId"
      - KeyName=$(cat test/test-instance-config.json | jq '.KeyName')
      - echo "$KeyName"
      - inspec exec test/inspec/test.rb -b ssh --host "$TestInstanceIpAddress" --user ec2-user -i "$KeyName" --sudo