version: 0.2
# Test AMI using InSpec tests

phases:
  install:
    commands:
      - echo Installing pre-reqs
      - apt-get -y update
      - apt-get -y install build-essential git curl build-essential libxml2-dev libxslt-dev libssl-dev autoconf jq wget

      - apt-get -y install autoconf bison  libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev 
      - git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      - echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      - echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      - source ~/.bashrc
      - type rbenv
      - git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      - rbenv install -l
     
      - rbenv install 2.7.1
      - rbenv global 2.7.1

      - ruby --version
      - wget https://packages.chef.io/files/stable/chefdk/3.1.0/ubuntu/14.04/chefdk_3.1.0-1_amd64.deb
      - dpkg -i chefdk_3.1.0-1_amd64.deb
      - export PATH="/home/ubuntu/.chefdk/gem/ruby/2.5.0/bin:$PATH"
      - chef gem update
  build:
    commands:
      - OUTPUTS=$(aws cloudformation describe-stacks --stack-name AMIPipelineTestInstance --output json --region us-east-2 | jq 'reduce .Stacks[0].Outputs[] as $item ({}; . + {"\($item.OutputKey)":$item.OutputValue})')
      - TestInstanceId=$(echo $OUTPUTS | jq -r '.TestInstanceId')
      - TestInstanceDnsName=$(echo $OUTPUTS | jq -r '.TestInstanceDnsName')
      - AmiId=$(cat cfn/test-instance-config.json | jq -r '.Parameters.AmiId')
      - KeyName=$(cat cfn/test-instance-config.json | jq -r '.Parameters.KeyName')
      - /root/.chefdk/gem/ruby/2.5.0/bin/inspec exec test/inspec/test.rb -b ssh --host $TestInstanceDnsName --user ec2-user -i "${KeyName}.pem" --sudo
    finally:
      - KeyName=$(cat cfn/test-instance-config.json | jq -r '.Parameters.KeyName')
      - aws ec2 delete-key-pair --key-name $KeyName